### ISSUE TITLE
Allow path navigation for templates

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#1076]
```twig
{% extends 'bar/foo.html.twig' %}
{% extends ':bar:foo.html.twig' %}
{% extends 'bar:sub:foo.html.twig' %}
{% extends '::foo.html.twig' %}
```
Split navigation target on directory seperator
```
'index' 'base.html.twig'
```

**Comment by King2500** [comment]
👍

**Comment by King2500** [comment]
Will we get this inside Controller and annotation as well?

`$this->render('bar/foo.html.twig');`
`@Template('bar/foo.html.twig')`

**Comment by Haehnchen** [comment]
yes its on the way ;)

**Comment by Haehnchen** [comment]
done

**Comment by King2500** [comment]
This is still not working with a custom `render` method (which has a placed `#Template` hash in it's PHPDoc):

```php
$this->render('@myModule/showFoo.html.php');
```

```php
class MyBaseController
{
    /**
     * @param string $template #Template
     * @param array $vars
     */
    protected function render($template, $vars)
    {
        //...
    }
}
```
The template file is resolved and goto works. But not path navigation when Ctrl+click on `@myModule`.

The `@myModule` package is defined via `ide-twig.json` and listed correctly in "Twig / Template" namespaces settings.
