### ISSUE TITLE
No installable verision 

### ISSUE THREAD

**Issue by Lehj14** [Haehnchen/idea-php-symfony2-plugin#1234]
Hi, I got this error:
`com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 25 path $
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 25 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at fr.adrienbrault.idea.symfony2plugin.installer.SymfonyInstallerUtil.getVersions(SymfonyInstallerUtil.java:114)
	at fr.adrienbrault.idea.symfony2plugin.installer.SymfonyInstallerForm.getVersions(SymfonyInstallerForm.java:54)
	at fr.adrienbrault.idea.symfony2plugin.installer.SymfonyInstallerForm.lambda$appendSymfonyVersions$3(SymfonyInstallerForm.java:63)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 25 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 10 more`

and once i tried creating a proj i dont have installable version.
![capture](https://user-images.githubusercontent.com/5898005/46245236-78b5b680-c3e2-11e8-8366-c14b65dab227.PNG)

PHPStorm 2018.2.4

**Comment by cedricziel** [comment]
Already fixed with #1227

**Comment by Lehj14** [comment]
@cedricziel  can you please let me know what should i do? you said its already fixed but i am still getting the above.

**Comment by Lehj14** [comment]
@cedricziel Not sure what should i do, uninstall and installed it but still getting the above.

**Comment by cedricziel** [comment]
I'll release a new version soon

**Comment by Lehj14** [comment]
@cedricziel Thank you. 👍 I though i am doing something wrong. Cant wait for it.
