### ISSUE TITLE
Doctrine Repository inspections defaulting to arrays

### ISSUE THREAD

**Issue by Lopton** [Haehnchen/idea-php-symfony2-plugin#1481]
Using 0.20.195 and I have the following code
`$userGroup = $this->getDoctrine()->getRepository(User\UserGroup::class)->findByTitle($userGroupTitle);`
In the repository I have the function findByTitle, which is clearly typehinted to return a single UserGroup object:
`public function findByTitle(string $title): UserGroup { ... }`
This used to not throw a warning, but now I get this warning later when I try to pass the UserGroup
`Expected parameter of type '\App\Entity\User\UserGroup', '\App\Entity\User\UserGroup[]' provided`

I would expect that if my repository returns a UserGroup through both typeHinting and @return annotation that the inspection would use those, not add an [ ] to the end of it and throw a warning.

**Comment by Lopton** [comment]
This appears to be related to pull request #1471 which allowed for type hinting the magic doctrine methods. Specifically the code here https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/c92446c07375de5b218064fa2e78787201827851

I am not very familiar with how the program works, but perhaps some logic to see if the user has manually overridden then magic methods by writing their own "findBy*" class before defaulting to the magic method determination.

**Comment by Haehnchen** [comment]
done as suggested ;)

**Comment by Lopton** [comment]
@Haehnchen Thanks, I'm still not seeing this change working in 20.200, the same errors persist for me as described in the original post. 

Maybe my problem would be caught by a second function in (src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/doctrine/fixtures/ObjectRepositoryResultTypeProvider.php)
```
   class BarRepository implements ObjectRepository
    {
        public function find() {}

        /**
         * @return Bar[]
         */
        public function findOneByFancyStuff() {}

        /**
         * @return Bar
         */
        public function findByFancyStuff() {}
    }
```

And then one more test (src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/doctrine/ObjectRepositoryResultTypeProviderTest.java)
```
public void testThatClassAsStringIsResolvedForMagicMethodsButNotWhenAlreadyExists() {
        // do nothing at all here; use type from the method it self
        assertPhpReferenceResolveTo(PhpFileType.INSTANCE,
            "<?php" +
                "/** @var \\Doctrine\\Common\\Persistence\\ObjectManager $om */\n" +
                "$om->getRepository('\\Foo\\Bar')->findOneByFancyStuff('foobar')[0]->get<caret>Id();",
            PlatformPatterns.psiElement(Method.class).withName("getId")
        );
        assertPhpReferenceResolveTo(PhpFileType.INSTANCE,
            "<?php" +
                "/** @var \\Doctrine\\Common\\Persistence\\ObjectManager $om */\n" +
                "$om->getRepository('\\Foo\\Bar')->findByFancyStuff('foobar')->get<caret>Id();",
            PlatformPatterns.psiElement(Method.class).withName("getId")
        );
        // repository class exists but method is magic
        assertPhpReferenceResolveTo(PhpFileType.INSTANCE,
            "<?php" +
                "/** @var \\Doctrine\\Common\\Persistence\\ObjectManager $om */\n" +
                "$om->getRepository('\\Foo\\Bar')->findOneByFancyStuffNotMagic('foobar')->get<caret>Id();",
            PlatformPatterns.psiElement(Method.class).withName("getId")
        );
    }
```
That would test my exact problem, I have a repository which is type hinted to return a single object with a findByTitle() class, but the inspection is assuming it returns an array.

Thanks for your work on this.
