### ISSUE TITLE
Multiple doctrine managers break bundle repository autocompletion

### ISSUE THREAD

**Issue by xmanoux** [Haehnchen/idea-php-symfony2-plugin#621]
On a bundle, I use secondary doctrine managers (to access foreign databases) , defined on the main config.yml

It breaks autocompletion of the ->getRepository("...") for every entity of this bundle

Please could you fix it ? Thank you very much for your work.

**Comment by icedevelopment** [comment]
Looks like it was fixed in 0.11.102.

**Comment by AITG** [comment]
Nope, still not fixed. We've got 2 entity managers, but the plugin only appears to pick up the last entity manager's config for a given name space.

i.e. given the config below, when we code complete on anything requiring an entity class (i.e. em->getReference(..) it only lists the first instance of a given namespace.

`orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
        entity_managers:
            default:
                hydrators:
                    ListHydrator: BlahBlah\WebsiteBundle\Hydrators\ListHydrator
                    PeopleHydrator: BlahBlah\WebsiteBundle\Hydrators\PeopleHydrator
                mappings:
                    OurBundlesDashboardBundle:
                        type: annotation
                        dir: "Entity"
                        prefix: "OurBundles\DashboardBundle\Entity"
                    BlahBlahWebsiteBundle:
                        type: annotation
                        dir: "Entity"
                        prefix: "BlahBlah\WebsiteBundle\Entity"
                    BlahBlahAdminBundle:
                        type: annotation
                        dir: "Entity"
                        prefix: "BlahBlah\AdminBundle\Entity"
                    tree:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                    loggable:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            zombies:
                connection: zombies
                mappings:
                    BlahBlahWebsiteBundle:
                        type: annotation
                        dir: "EntityZombies"
                        prefix: "BlahBlah\WebsiteBundle\EntityZombies"
`

Note that BlahBlahWebsiteBundle is in both entity managers, the plugin only appears to pick up  the last reference per namespace. When we auto complete on $em->getReference() it returns the matches from all the mappings under the default, but the only matches from BlahBlahWebsiteBundle come from the zombies manager, not the default manager.

**Comment by AITG** [comment]
Note, this did work fine until an update of the plugin a few months ago.... I can't recall the version that broke it, but it was probably when I upgraded to PHPStorm 2016, so that may have a bearing on it too. Sorry, so much uncertainty when bug hunting isn't useful, I know :(

**Comment by Protocteur** [comment]
I have this problem too since my last plugin update ~ 2 weeks ago
The instance of repository after using $em->getRepository('...') is recognized as Doctrine/Common/Persistence/ObjectRepository

When i'm using the default manager autocompletion works but not when i'm using one of the others manager instance.

ps: does anyone know a way to downgrade plugins in phpstorm while this issues is fixed ? it's a bit frustration to not have this autocompletion on repositories :'(
ps2: thx for the work on the plugin :p
